
import { Montserrat } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
const inter = Montserrat({ 
  subsets: ["latin"],
  weight:["100","300","400","500","600","700","900"],
  variable:"--globalFont"
 });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark'>
      <body className={inter.className}>
        <AntdRegistry>
        {children}
        </AntdRegistry>
        </body>
    </html>
  );
}
